### ISSUE TITLE
Request: Option to not allow authenticated users access

### ISSUE THREAD

**Issue by nickdekruijk** [spatie/laravel-demo-mode#28]
Unless I'm missing something it looks like authenticated users are allowed access to the demomode protected pages even when they didn't visit the demoAccess url. Would be nice to prevent that somehow. I have new functionality in my web app where users can login already that I only want a few people to be able to test.

**Comment by freekmurze** [comment]
I'm thinking there should be an easy way to register your own [DemoGuard](https://github.com/spatie/laravel-demo-mode/blob/master/src/DemoGuard.php) in the config file. So we should have an interface for that and by default the current one is specified.

With that in place you can change the behaviour to your heart's content.

Because I don't need this myself, I'm not going to invest any time it, but feel free to send a fully tested PR for this.

**Comment by freekmurze** [comment]
We'll handle this further in #30
